In [ ]:
# 뇌를 자극하는 파이썬 예제
# https://www.hanbit.co.kr/media/community/brain_default_board_view.html?bd_id=python&board_idx=19250&page=0

# 자바와 파이썬의 차이
# https://m.blog.naver.com/PostView.nhn?blogId=magnking&logNo=220907439135&proxyReferer=https:%2F%2Fwww.google.com%2F

# 파이썬코딩 한시간만에 배우기
# https://www.youtube.com/watch?v=M6kQTpIqpLs

# numpy 예제
# http://pythonstudy.xyz/python/article/402-numpy-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0

# pandas 예제
# http://pythonstudy.xyz/python/article/408-pandas-%EB%8D%B0%EC%9D%B4%ED%83%80-%EB%B6%84%EC%84%9D

# dataframe 예제
# http://pythonstudy.xyz/python/article/408-pandas-%EB%8D%B0%EC%9D%B4%ED%83%80-%EB%B6%84%EC%84%9D

# 케라스를 활용한 간단한 예제 살펴보기
# https://cyc1am3n.github.io/2018/11/02/introduction-to-keras.html

# 케라스 김태영 T아카데미 1,2강
# https://www.youtube.com/watch?v=cJpjAmRO_h8
# https://www.youtube.com/watch?v=IPR2bYFa6Rw
# https://www.youtube.com/watch?v=QldOyLAQfVg

# 케라스 김태영 블로그
# https://tykimos.github.io/lecture/

# 코딩셰프 케라스맛
# https://github.com/jskDr/keraspp.git

# 케라스 창시자에게서 배우는 딥러닝
# https://github.com/gilbutITbook/006975

# 코랩 소개
# https://colab.research.google.com/notebooks/welcome.ipynb#scrollTo=C4HZx7Gndbrh

# 코랩 끊김 방지
# https://teddylee777.github.io/colab/google-colab-%EB%9F%B0%ED%83%80%EC%9E%84-%EC%97%B0%EA%B2%B0%EB%81%8A%EA%B9%80%EB%B0%A9%EC%A7%80

# 이미지 분류
# https://colab.research.google.com/github/tensorflow/hub/blob/master/examples/colab/tf2_image_retraining.ipynb#scrollTo=dlauq-4FWGZM








In [1]:
###########################################################################################################################################################

# 파이썬 예제
print("Hello, World.")



###########################################################################################################################################################


Hello, World.


In [2]:

# 입력받아 연산
print("첫 번째 수를 입력하세요. : ")
a = input()
print("두 번째 수를 입력하세요. : ")
b = input()

result = int(a) * int(b)

print("{0} * {1} = {2}".format(a, b, result))



첫 번째 수를 입력하세요. : 
1
두 번째 수를 입력하세요. : 
2
1 * 2 = 2


In [ ]:

###########################################################################################################################################################
# 파이썬 예제
for s in ['뇌를', '자극하는', '파이썬'] :
    print(s)




In [ ]:

###########################################################################################################################################################
# 파이썬 예제
for s in '뇌를 자극하는 파이썬' :
    print(s)




In [ ]:

###########################################################################################################################################################
# 파이썬 예제 for
for i in (1, 2, 3) :
	print(i)




In [ ]:

###########################################################################################################################################################
# 파이썬 예제 for range
for i in range(1, 6) :
        for j in range(i) :
            print( "*", end = "", )
        
        print()



In [ ]:

###########################################################################################################################################################
import keras
keras.__version__

###########################################################################################################################################################
# 쥬피터에서
# ipynb 를 import 하기

!pip install import_ipynb
import import_ipynb
!pwd
%cd "/content/drive/My Drive/Colab Notebooks"



In [ ]:


import calculator

print(calculator.plus(10, 5))
print(calculator.minus(10, 5))
print(calculator.multiply(10, 5))
print(calculator.divide(10, 5))



In [ ]:


###########################################################################################################################################################
# numpy 예제

import numpy as np
 
list1 = [1, 2, 3, 4]
a = np.array(list1)
print(a.shape) # (4, )
 
b = np.array([[1,2,3],[4,5,6]])
print(b.shape) # (2, 3)
print(b[0,0])  # 1  



In [ ]:

###########################################################################################################################################################
import numpy as np
 
a = np.zeros((2,2))
print(a)
# 출력:
# [[ 0.  0.]
#  [ 0.  0.]]
 
a = np.ones((2,3))
print(a)
# 출력:
# [[ 1.  1.  1.]
#  [ 1.  1.  1.]]
 
a = np.full((2,3), 5)
print(a)
# 출력:
# [[5 5 5]
#  [5 5 5]]
 
a = np.eye(3)
print(a)
# 출력:
# [[ 1.  0.  0.]
#  [ 0.  1.  0.]
#  [ 0.  0.  1.]]
 
a = np.array(range(20)).reshape((4,5))
print(a)
# 출력:
# [[ 0  1  2  3  4]
#  [ 5  6  7  8  9]
#  [10 11 12 13 14]
#  [15 16 17 18 19]]


In [ ]:


###########################################################################################################################################################
# slice 예제
a = ['a', 'b', 'c', 'd', 'e']

print("a[ 1 :  ] = ",a[ 1 :  ])
print("a[  : 2 ] = ",a[  : 2 ])
print("a[ 2 : 4 ] = ",a[ 2 : 4 ])
print("a[ : : 2 ] = ", a[ : : 2 ])


In [ ]:

###########################################################################################################################################################
# pandas 예제
import pandas as pd
 
data = {
    'year': [2016, 2017, 2018],
    'GDP rate': [2.8, 3.1, 3.0],
    'GDP': ['1.637M', '1.73M', '1.83M']
}
 
df = pd.DataFrame(data)

print(df)


In [ ]:

###########################################################################################################################################################
# 케라스 창시자에게서 배우는 딥러닝
! git clone https://github.com/gilbutITbook/006975.git




In [ ]:

###########################################################################################################################################################
# 코딩셰프 케라스맛
! git clone https://github.com/jskDr/keraspp.git



In [ ]:

###########################################################################################################################################################
# 코딩셰프 케라스맛
import keras
import numpy

x = numpy.array([0, 1, 2, 3, 4])
y = x * 2 + 1

model = keras.models.Sequential()
model.add(keras.layers.Dense(1, input_shape=(1,)))
model.compile('SGD', 'mse')

model.fit(x[:2], y[:2], epochs=1000, verbose=0)

print('Targets:', y[2:])
print('Predictions:', model.predict(x[2:]).flatten())



In [ ]:

###########################################################################################################################################################
# 코딩셰프 케라스맛 응용
import keras
import numpy

x = numpy.array([(1,1), (1,2), (1,3), (1,4), (1,5)])
for i in range(0, 5):
  y[i] = x[i][0] * 2 + x[i][1] * 1

model = keras.models.Sequential()
model.add(keras.layers.Dense(4, input_shape=(2,)))
model.add(keras.layers.Dense(3))
model.add(keras.layers.Dense(1))
model.compile('SGD', 'mse')

print('x:', x[2:])

model.fit(x[:2], y[:2], epochs=10000, verbose=0)

print('Targets:', y[2:])
print('Predictions:', model.predict(x[2:,:]))



In [ ]:

##############################################
# Plotting
##############################################
import matplotlib.pyplot as plt


def plot_acc(history, title=None):
    # summarize history for accuracy
    if not isinstance(history, dict):
        history = history.history

    plt.plot(history['acc'])
    plt.plot(history['val_acc'])
    if title is not None:
        plt.title(title)
    plt.ylabel('Accuracy')
    plt.xlabel('Epoch')
    plt.legend(['Training', 'Verification'], loc=0)
    # plt.show()


def plot_loss(history, title=None):
    # summarize history for loss
    if not isinstance(history, dict):
        history = history.history

    plt.plot(history['loss'])
    plt.plot(history['val_loss'])
    if title is not None:
        plt.title(title)
    plt.ylabel('Loss')
    plt.xlabel('Epoch')
    plt.legend(['Training', 'Verification'], loc=0)
    # plt.show()


##############################################
# Main
##############################################
def main():
    Nin = 784
    Nh = 100
    number_of_class = 10
    Nout = number_of_class

    # model = ANN_models_func(Nin, Nh, Nout)
    # model = ANN_models_class(Nin, Nh, Nout)
    model = ANN_seq_class(Nin, Nh, Nout)
    (X_train, Y_train), (X_test, Y_test) = Data_func()

    ##############################################
    # Training
    ##############################################
    history = model.fit(X_train, Y_train, epochs=15, batch_size=100, validation_split=0.2)
    performace_test = model.evaluate(X_test, Y_test, batch_size=100)
    print('Test Loss and Accuracy ->', performace_test)

    plot_loss(history)
    plt.show()
    #plot_acc(history)
    #plt.show()


# Run code
if __name__ == '__main__':
    main()



In [ ]:

###########################################################################################################################################################
# 간단한 prediction 예제


import keras
import numpy

x = numpy.array([0, 1, 2, 3, 4])
y = x * 2 + 1

model = keras.models.Sequential()
model.add(keras.layers.Dense(1, input_shape=(1,)))
model.compile('SGD', 'mse')

model.fit(x[:2], y[:2], epochs=1000, verbose=0)

print('Targets:', y[2:])
print('Predictions:', model.predict(x[2:]).flatten())



In [ ]:
###########################################################################################################################################################
# rnn exam
# https://github.com/alucard001/RNN-Example/blob/master/Keras%20RNN%20Example.ipynb

from pandas import DataFrame
from pandas import concat
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.layers import LSTM

import numpy as np


values = np.random.random((100, 2))

input_train, target_train = values[0:70, 0], values[0:70, 1]
input_test , target_test  = values[70:, 0], values[70:, 1]

input_train = input_train.reshape(len(input_train), 1, 1)
input_test = input_test.reshape(len(input_test), 1, 1)

epochs = 10
batchsize = 10
timestep = 1
input_dim = 1

batchsize

# Build model
model = Sequential()
model.add(LSTM(10, activation='sigmoid', batch_input_shape=(batchsize, timestep, input_dim), return_sequences=True, stateful=True))
model.add(Dropout(0.5))
model.add(LSTM(8, stateful=True))
model.add(Dropout(0.5))
model.add(Dense(1, activation='tanh'))
model.compile(optimizer='rmsprop',
              loss='mse', metrics=['accuracy'])


# history = model.fit(inputs, y, epochs=100, batch_size=len(values), verbose=0)
history = model.fit(input_train, target_train, epochs=epochs, 
                   batch_size=batchsize, shuffle=False,
                   validation_data=(input_test, target_test))


# new_values = np.random.random(100).reshape(100, 1, 1)
predict = model.predict(input_test, batch_size=batchsize)

import matplotlib.pyplot as plt 
plt.plot(input_test.reshape(30,1), color='red', label="input test")
plt.plot(predict.reshape(30,1), color='blue', label="prediction")
plt.plot(target_test.reshape(30,1), color='orange', label="target test")
plt.title("Random RNN")
plt.xlabel('X')
plt.ylabel('Y')
plt.legend()
plt.show()



In [ ]:


import pandas as pd
import matplotlib.pyplot as plt
import datetime
from mpl_finance import candlestick_ohlc
import matplotlib.dates as mdates
from Investar import Analyzer
import numpy as np

mk = Analyzer.MarketDB()

for keys in mk.codes:

    print(f"keys:{keys} company:{mk.codes[f'{keys}']}")
    
df = mk.get_daily_price('삼성전자', '2021-06-18')
print(f"df:{df}")
